### ISSUE TITLE
Unhandled Exception: System.IndexOutOfRangeException: Could not find specified column in results: ServerFlags

### ISSUE THREAD

**Issue by sonjamichelle** [HalcyonGrid/halcyon#22]
Just playing around with Halcyon again. Have a single standalone region at the moment with whip and mysql running on a separate Linux box. Halcyon.exe running on a Win10 box. Current version, 0.9.41. Everything WAS running fine. Started ok, logged in (still a cloud ;-) ), loaded an oar from my previous grid. Then tonight I fired up Halcyon.exe and I get the following error. Note the first line in bold.

`**Unhandled Exception: System.IndexOutOfRangeException: Could not find specified column in results: ServerFlags**
   at MySql.Data.MySqlClient.ResultSet.GetOrdinal(String name)
   at MySql.Data.MySqlClient.MySqlDataReader.get_Item(String name)
   at OpenSim.Data.MySQL.MySQLDataStore.BuildPrim(IDataReader row) in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Data\MySQL\MySQLRegionData.cs:line 1764
   at OpenSim.Data.MySQL.MySQLDataStore.LoadObjects(UUID regionUUID) in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Data\MySQL\MySQLRegionData.cs:line 858
   at OpenSim.Region.Framework.Scenes.Scene.LoadPrimsFromStorage(UUID regionID) in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Region\Framework\Scenes\Scene.cs:line 2147
   at OpenSim.OpenSimBase.CreateRegion(RegionInfo regionInfo, Boolean portadd_flag, Boolean do_post_init, IScene& mscene) in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Base\OpenSimBase.cs:line 470
   at OpenSim.OpenSimBase.CreateRegion(RegionInfo regionInfo, Boolean portadd_flag, IScene& scene) in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Base\OpenSimBase.cs:line 395
   at OpenSim.ApplicationPlugins.LoadRegions.LoadRegionsPlugin.PostInitialize() in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\ApplicationPlugins\LoadRegions\LoadRegionsPlugin.cs:line 119
   at OpenSim.OpenSimBase.StartupSpecific() in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Base\OpenSimBase.cs:line 211
   at OpenSim.OpenSim.StartupSpecific() in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Base\OpenSim.cs:line 163
   at OpenSim.Framework.Servers.BaseOpenSimServer.Startup() in C:\Users\sonja\Desktop\halcyon-0.9.41\OpenSim\Framework\Servers\BaseOpenSimServer.cs:line 300
   at OpenSim.Application.Main(String[] args) in C:\Users\sonja\Desktop\halcyon-0.9.41\InWorldz\Halcyon\Application.cs:line 153`

I remember coming across this before but for the life of me I can't remember how I resolved it. Might have to pick through the issues on the old github project. I don't remember if I posted an issue before.

Anyhoo, I think halcyon.exe is looking for the column ServerFlags in one of the tables, though it can't find it. Which table, I'm not sure and I don't remember.

**Comment by sonjamichelle** [comment]
Further digging into the .cs source files tells me that the ServerFlags column is supposed to be in the prims table.

Looking at the sql source files called up by hc-databse.exe there is no creation of ServerFlags for the table prims. I can add the column manually to get things working again, but I need to know the format of the column and what value is supposed to be in it.

It also looks like the source .sql needs to be amended to include the creation code.

**Comment by sonjamichelle** [comment]
OH WOW! I hadn't realized InWorldz shut down. That sort of explains the new github.

Well digging around I found the following:

`Halcyon Server 0.9.32 Release Notes R6272 – InWorldz
https://inworldz.zendesk.com/.../115004375488-Halcyon-Server-0-9-32-Release-Note...

Mar 10, 2017 - Halcyon Server 0.9.32 R6272 is now running on all InWorldz and ... prims` ADD COLUMN `ServerFlags` INT(11) NOT NULL DEFAULT '0' ...
You've visited this page 2 times. Last visit: 9/13/18`

HOWEVER, I can't seem to find anyplace where those release notes are archived. Unfortunately everything is gone.

**Comment by sonjamichelle** [comment]
What is the difference between the two files?

inworldz-core-base.sql

and

inworldz-rdb-base.sql

running the required hc-database.exe command during configuration one would assume that inworldz-core-base.sql would be the sql read, however it seems that inworldz-rdb-base.sql is being read.

To fix this issue I added the line:

`ServerFlags` int(11) NOT NULL DEFAULT '0',

round about line 214 in inworldz-rdb-base.sql. The column was created in the DB as expected.

I want to contribute a PR but I'm not sure which file to submit for patching. Or should I submit both files with the patched line?

**Comment by zauberparacelsus** [comment]
I am seeing this issue as well on my private Halcyon installation.  It is triggered on startup whenever any mesh objects are on the region.  Only workaround I've found so far is to manually delete them from the prims database table.

**Comment by zauberparacelsus** [comment]
Okay, read back and saw the workaround

**Comment by sonjamichelle** [comment]
I suppose this issue can be closed now that Pull Requests #24 and #25 are committed to the master branch.
