### ISSUE TITLE
Asset Server "WHIP" Could not be loaded

### ISSUE THREAD

**Issue by DJShocker** [HalcyonGrid/halcyon#45]
Same machine, WHIP is running fine and listening, 
```
2018-12-20 07:29:13,406 [1] INFO  OpenSim.Application - [HALCYON MAIN]: configured log4net using default Halcyon.exe.config
2018-12-20 07:29:13,421 [1] INFO  OpenSim.Application - Performing compatibility checks... 
2018-12-20 07:29:13,421 [1] INFO  OpenSim.Application - Environment is compatible.

2018-12-20 07:29:13,437 [ConsoleThread] INFO  OpenSim.ConfigurationLoader - [CONFIG] Reading configuration settings
2018-12-20 07:29:13,437 [ConsoleThread] INFO  OpenSim.ConfigurationLoader - [CONFIG] Reading configuration file C:\Users\Administrator\Documents\halcyon-master\halcyon-master\bin\Halcyon.ini
2018-12-20 07:29:13,484 [ConsoleThread] INFO  OpenSim.Framework.Servers.BaseOpenSimServer - [STARTUP]: Beginning startup processing
2018-12-20 07:29:13,484 [ConsoleThread] INFO  OpenSim.OpenSim - ====================================================================
2018-12-20 07:29:13,484 [ConsoleThread] INFO  OpenSim.OpenSim - ========================= STARTING HALCYON =========================
2018-12-20 07:29:13,484 [ConsoleThread] INFO  OpenSim.OpenSim - ====================================================================
2018-12-20 07:29:13,484 [ConsoleThread] INFO  OpenSim.OpenSim - [HALCYON MAIN]: Running in grid mode
2018-12-20 07:29:13,484 [ConsoleThread] INFO  OpenSim.OpenSim - GC: Server mode: False, Interactive
2018-12-20 07:29:13,499 [ConsoleThread] INFO  OpenSim.Region.Framework.StorageManager - [DATASTORE]: Attempting to load OpenSim.Data.MySQL.dll
2018-12-20 07:29:13,515 [ConsoleThread] INFO  OpenSim.Region.Framework.StorageManager - [DATASTORE]: Added IRegionDataStore Interface
2018-12-20 07:29:13,515 [ConsoleThread] INFO  OpenSim.Region.ClientStack.ClientStackManager - [CLIENTSTACK]: Attempting to load OpenSim.Region.ClientStack.LindenUDP.dll
2018-12-20 07:29:13,531 [ConsoleThread] INFO  OpenSim.Region.ClientStack.ClientStackManager - [CLIENTSTACK]: Added IClientNetworkServer Interface
2018-12-20 07:29:13,546 [ConsoleThread] DEBUG OpenSim.OpenSimBase - [HALCYONBASE] Attempting to load asset server id=WHIP
2018-12-20 07:29:13,546 [ConsoleThread] INFO  OpenSim.Framework.PluginLoader`1 - [PLUGINS]: Initializing addin manager
2018-12-20 07:29:13,624 [ConsoleThread] INFO  OpenSim.Framework.PluginLoader`1 - [PLUGINS]: Loading extension point /OpenSim/AssetClient
2018-12-20 07:29:13,624 [ConsoleThread] ERROR OpenSim.Application - [APPLICATION]: 
APPLICATION EXCEPTION DETECTED: System.UnhandledExceptionEventArgs

Exception: System.Exception: Asset server WHIP could not be loaded
   at OpenSim.OpenSimBase.InitializeAssetCache() in C:\Users\Administrator\Documents\halcyon-master\halcyon-master\OpenSim\Base\OpenSimBase.cs:line 324
   at OpenSim.OpenSimBase.Initialize() in C:\Users\Administrator\Documents\halcyon-master\halcyon-master\OpenSim\Base\OpenSimBase.cs:line 286
   at OpenSim.Region.ClientStack.RegionApplicationBase.StartupSpecific() in C:\Users\Administrator\Documents\halcyon-master\halcyon-master\OpenSim\Region\ClientStack\RegionApplicationBase.cs:line 107
   at OpenSim.OpenSimBase.StartupSpecific() in C:\Users\Administrator\Documents\halcyon-master\halcyon-master\OpenSim\Base\OpenSimBase.cs:line 201
   at OpenSim.OpenSim.StartupSpecific() in C:\Users\Administrator\Documents\halcyon-master\halcyon-master\OpenSim\Base\OpenSim.cs:line 163
   at OpenSim.Framework.Servers.BaseOpenSimServer.Startup() in C:\Users\Administrator\Documents\halcyon-master\halcyon-master\OpenSim\Framework\Servers\BaseOpenSimServer.cs:line 300
   at OpenSim.Application.Main(String[] args) in C:\Users\Administrator\Documents\halcyon-master\halcyon-master\InWorldz\Halcyon\Application.cs:line 153

Application is terminating: True
```

**Comment by DJShocker** [comment]
Thank you, emperor and I was originally nervous to even post here about it as I've ran into some toxic people when it comes to a noob like me asking questions in other projects. I do this to teach myself, this is something i enjoy doing, I find it fascinating. 

Now, when you say "key" i'm assuming the password, kinda like: 
WhipURL = "whip://changeme@127.0.01:32700"

Where changeme is the password.

I've already done the firewall check, all added and tested, visible. Still getting the error

**Comment by kf6kjg** [comment]
Invited DJShocker onto the Discord and we continued resolving setup support there.
